name: Get available languages

on:
  schedule: 
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  availableLanguages:
    runs-on: ubuntu-latest
    steps:
    - name: Get available languages and output to json
      run: /availableLanguages.sh
