# This is a basic workflow to help you get started with Actions

name: availableLanguages

# Controls when the action will run. 
on:
  schedule: 
    - cron: "0 */2 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  availableLanguages:
    runs-on: ubuntu-latest
    steps:
    - name: Get available languages and output to json
      run: curl -X GET https://crowdin.com/api/v2/projects/428718/languages/progress -H "Authorization: Bearer 619136399475cf3a9457e59502df76a0c5f8ab401982954197fb501dab44f6668bed46b72fb123ae" -o availableLanguages.json
      
