name: availableLanguages


on:
  schedule: 
    - cron: "0 */2 * * *"
    
  workflow_dispatch:


jobs:
  availableLanguages:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SECRETPAT: ${{ secrets.CROWDINPAT_availableLanguages }}
      run: |
        curl -X GET https://crowdin.com/api/v2/projects/428718/languages/progress -H "Authorization: Bearer $SECRETPAT" -o availableLanguages.json
