name: availableLanguages


on:
  schedule: 
    - cron: "0 */2 * * *"
    
  workflow_dispatch:


jobs:
  availableLanguages:
    runs-on: ubuntu-latest
    steps:
    - name: Get available languages and output to json
      run: curl -X GET https://crowdin.com/api/v2/projects/428718/languages/progress -H "Authorization: Bearer 619136399475cf3a9457e59502df76a0c5f8ab401982954197fb501dab44f6668bed46b72fb123ae" -o availableLanguages.json
      
