name: Update strings.json

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Pull origin
        run: |
          git pull
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate strings.json
        run: node generate-strings.js

      - name: Commit changes
        run: |
          git config --local user.email "quinten@althues.nl"
          git config --local user.name "QkeleQ10"
          git add strings.json
          git commit -m "Update strings.json" || echo "No changes to commit"
