name: Update strings.json

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-strings:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate strings.json
        run: node generate-strings.js

      - name: Config GitHub
        run: |
          git config --local user.email "quinten@althues.nl"
          git config --local user.name "QkeleQ10"

      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          ref: updates

      - name: Commit changes
        run: |
          git pull
          git add strings.json
          git commit -m "Update strings.json" || echo "No changes to commit"
