name: Combine translation files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-strings:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate strings.json
        run: node generate-strings.js

      - name: Commit artifacts
        if: github.event_name == 'push'
        run: |
          git config --global user.name "Continuous Integration"
          git config --global user.email "quinten@althues.nl"
          git commit -a -m "Update strings.json" || echo "No changes to commit"
          git push
